// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DropZoneController from "./drop_zone_controller"
application.register("drop-zone", DropZoneController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import FlashController from "./flash_controller"
application.register("flash", FlashController)

import FormChangedCheckController from "./form_changed_check_controller"
application.register("form-changed-check", FormChangedCheckController)

import FormController from "./form_controller"
application.register("form", FormController)

import GoongMapController from "./goong_map_controller"
application.register("goong-map", GoongMapController)

import ImageFilePreviewController from "./image_file_preview_controller"
application.register("image-file-preview", ImageFilePreviewController)

import NavbarController from "./navbar_controller"
application.register("navbar", NavbarController)

import NestedFormController from "./nested_form_controller"
application.register("nested-form", NestedFormController)

import PriceController from "./price_controller"
application.register("price", PriceController)

import RedirectController from "./redirect_controller"
application.register("redirect", RedirectController)

import SideModalController from "./side_modal_controller"
application.register("side-modal", SideModalController)

import VendorSpendingController from "./vendor_spending_controller"
application.register("vendor-spending", VendorSpendingController)
