default: &default
  dispatchers:
    - polling_interval: 1
      batch_size: 500
      recurring_tasks:
        my_recurring_task:
          class: UpdateScheduledBoostingsJob
          schedule: every 2s
  workers:
    - queues: "*"
      threads: 3
      processes: 1
      polling_interval: 0.1

development:
 <<: *default

test:
 <<: *default

production:
 <<: *default
